server:
  port: 8090

app:
  config:
    api-version: v1
    cross-origin: '*'
    group-buy-market:
      api-url: http://127.0.0.1:8091
      notify-http-open: false
      notify-url: http://127.0.0.1:8090/api/v1/pay-mall/settlement
    weixin:
      api-url: https://api.weixin.qq.com

# 线程池配置
thread:
  pool:
    executor:
      config:
        core-pool-size: 20
        max-pool-size: 50
        keep-alive-time: 5000
        block-queue-size: 5000
        policy: CallerRunsPolicy

# 数据库配置；启动时配置数据库资源信息
spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://192.168.31.25:13306/s-pay-mall-ddd-market?useUnicode=true&characterEncoding=utf8&autoReconnect=true&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai&useSSL=true
    driver-class-name: com.mysql.cj.jdbc.Driver
  hikari:
    pool-name: Retail_HikariCP
    minimum-idle: 15 #最小空闲连接数量
    idle-timeout: 180000 #空闲连接存活最大时间，默认600000（10分钟）
    maximum-pool-size: 25 #连接池最大连接数，默认是10
    auto-commit: true  #此属性控制从池返回的连接的默认自动提交行为,默认值：true
    max-lifetime: 1800000 #此属性控制池中连接的最长生命周期，值0表示无限生命周期，默认1800000即30分钟
    connection-timeout: 30000 #数据库连接超时时间,默认30秒，即30000
    connection-test-query: SELECT 1
  type: com.zaxxer.hikari.HikariDataSource


  # RabbitMQ
  rabbitmq:
    addresses: 192.168.31.25
    port: 5672
    username: admin
    password: admin
    listener:
      simple:
        prefetch: 1 # 每次投递n个消息，消费完在投递n个
    template:
      delivery-mode: persistent # 确保全局默认设置为持久化（可选）
    config:
      producer:
        topic_order_pay_success:
          exchange: s_pay_mall_exchange
          routing_key: topic.order_pay_success
          queue: s_pay_mall_queue_2_order_pay_success

      consumer:
        topic_team_success:
          exchange: group_buy_market_exchange
          routing_key: topic.team_success
          queue: s_pay_mall_queue_2_topic_team_success
        topic_order_pay_success:
          exchange: s_pay_mall_exchange
          routing_key: topic.order_pay_success
          queue: s_pay_mall_queue_2_order_pay_success


mybatis:
  mapper-locations: classpath:/mybatis/mapper/*.xml
  config-location:  classpath:/mybatis/config/mybatis-config.xml


# 微信公众号对接
weixin:
  config:
    originalid: gh_db9fa16cd310
    token: gzc1106
    app-id: wx428512269871be01
    app-secret: acee42440c5432ca93bbc1807337780c
    template:
      template-id: JY2vnuKYYsJQV283j3S9e8JXCoZmgnow6IEm2rMqnZE
      template-notify-url: http://7e16413b.r32.cpolar.top/api/v1/weixin/template/send-notify


# 支付宝支付 - 沙箱 https://opendocs.alipay.com/common/02kkv7
alipay:
  enabled: true
  # 应用ID
  app_id: 2021000148699605
  # 商户私钥
  merchant_private_key: MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCYvKeT3NnBdA0ioV8oLHX1qPC4Loba9PCqe1DYrl2swgDx+61uQjob0jJVOGFMcmenPIx8B6IxfFM0su5BF8Yz9bOkiNILF1I8ANb9WH3CwKQ1lAqwhn8LBBcvfh1ZTBh2ecfAO93ZUUJxLYjwaUuYMdvrs/0pkGkQjt5+KfUG8YIipOu4vsQG79NEQwV8129CWH4qlcUf0CpQOfiiHKNnR0JD6vAlF0yQlT+gqwdOAjJ81PjabZVlNQ2LCfMYWXCs6dV+Tnh8PjN20HQJYxAz1Td7/c9zPD1WkkeXaiI4y0O5uWumwfjBgJKL8HYM7shIHXtlrL8OCVNCsW2fT+bpAgMBAAECggEAWD01e0EuNIs9Q3KDLQxyoZgWafHHSxwTJgrULDqgN7xlG2fRTE/KjmQjXASUgbvekklyx/0JARnYYCu3Zbe8dCxQuo+o+WthwPSjP/4tuaPdum5qto0dPFoCoxdzETHbOCcm9bIgevptLkGmSW4rlCPJ8CQt8CNT75L6i1zmCDn9ySvKLojIh/Z2CIThl7K8t3HI9axCQ7/sFsg6+WGxp7ERlQ45SheyuGaIp+WxLzM/5vL+MB8qRDZA0mD8L55d2SKB6POiTaaI4KUUNV9+IoWzwOBwn9F0BdHa/j4PH6Sz1eFNAhG+3zzQdYU5Z9OC26ERBKME+JZVUI6Fqbr6AQKBgQDOguYIrPTli3hQL0lQX2DpR+rK/KQFVSfIoB2cHRiS+JO/ketjlIudlsMmFo9xt/pA+rvpjbfHK0LpYuaa4AesTwkabeZ7o/qCckzk5+mXZeGAcNh9yMajczqPQ1xtCsH8MTH0dRWucU+mZC1AICoF/E478iTpVdryxW0WkWnh4QKBgQC9VssFbqyZOh41IULuwkNWNumevJaJ0nWJd5xC+kfxDNhrTM75Dk0KWUUF2O4Eyp5E0h6mh/HDVMj8ANsMRZvLX/izFtwShtMR8Of5PbZM/ZSUjnbdZSeP6cRNdQBg6GUhOCRZ3gr/YHYNlNbrrXnIsr7eDHIzdk2FQ+r63iG2CQKBgB72XUr7s5Qe/yD2lgVo53zSfY+FpYnvJJHd/9KCQkb24iAc3rAFe5FbI1M4mrUwImNPtJDl4KIKCHQ5kd2yrTPWfcTqqV3sTgj03jaL1ugOLGs3gB4L1kx3YFZOgTMQI9mN/rFqRJ/s+UY3StmMeQCAvbIbMhGR/8vaceqqTrfBAoGAKsQ2+VQlUjrpZdDMgIeKlCe1HzCzxA+wkstclVhY9Z6UJ7Bis6jCSAsf5xE3ugdWNm9Lkwvz1M4K07kRwTTb2tUjpLgOH3UqqcvDae3BhqRkciW3vYxComQH/gLmgf0cEqPOuinITCSqpaiv3u4BKw8Mw7UF+o/HNMnBgsa30JkCgYEAiFOCoR+BJfKZx1ur497Ua5bv+w8GLJtECu8gPZETJsF1WsbyFUQLED7mB2DSrHys6pxlBO6Xy0vIl90ZO+pXG67xPOB9lORBOCJpUkNmtb+aLXFGDUtxQjv7yfOHwFpap3tPuiTJuWOQs246OSkwEvX5TnnV7avloPTwNVaay+A=
  # 支付宝公钥
  alipay_public_key: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAu+q0f+zJ33m+TyN8GXI18wwaxY325Wl6iXA6/eizuj0DL+t81Nu7hou621a1/BVKq55SP3CPnrpu/r9YP7sMunxQRg9FDKddrVfUcz6OLsO96diNzSn9/OpPC9ibX34Q1YNoFAowNo5AnaVmULnnds+rarTX4g1lYrq/lsTmns9uBXZvS0/THsWFbIEnFJi2Mdnbp+9tes2KrTm1tZwsCZo+1zKPRyXafx1pSgIAd2AH3lPSyhFaSSIyPzO8eT1A3bGltpH8TFmqpCVd6xaeO3FLsjRNg9zQ0CQKd8DI06PPIajWmHZ1Z+Qh0vVe4xAAhGGnxxZssaYT9OMuyVomZwIDAQAB
  # 内网穿透 服务器异步通知回调地址，也就是用户支付完成后，支付宝调用开发者的地址
  notify_url: http://7e16413b.r32.cpolar.top/api/v1/alipay/alipay_notify_url
  # 内网穿透 用户支付完成后跳转的地址
  return_url: https://baidu.com
  # 固定的 支付宝沙箱环境的地址
  gatewayUrl: https://openapi-sandbox.dl.alipaydev.com/gateway.do


# 日志
logging:
  level:
    root: info
  config: classpath:logback-spring.xml